nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

proxy:
  # - name: kubeapi
  #   service:
  #     port: 6443
  #     extras:
  #       type: LoadBalancer
  #       loadBalancerIP: "192.168.1.123"
  #   ingress:
  #     enabled: true
  #     hosts:
  #       - kubeapi.lan
  #     paths: ['/']
      
  #   backend:
  #     ip: 192.168.22.11
  #     port: 6443
